# Site settings
baseURL = "https://SukeshKrk.github.io/"
title = "SukeshBaseData"
theme = "hugo-PaperMod"
enableRobotsTXT = true

# Author & description
[params]
  author = "Kotha Sukesh Kumar Reddy"
  description = "Oracle, Exadata, PostgreSQL & DBA knowledge shared with DBA tech friends."
  defaultTheme = "auto"          # auto / dark / light
  ShowReadingTime = true
  ShowToc = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowShareButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true

# URL handling for GitHub Pages
relativeURLs = true       # Generates relative URLs for menus & assets
canonifyURLs = false      # Prevents Hugo from forcing absolute URLs

[pagination]
  pagerSize = 10

# Menu
[menu]
  [[menu.main]]
    identifier = "oracle"
    name = "Oracle"
    url = "/oracle/"
    weight = 1

  [[menu.main]]
    identifier = "postgresql"
    name = "PostgreSQL"
    url = "/postgresql/"
    weight = 2

  [[menu.main]]
    identifier = "exadata"
    name = "Exadata"
    url = "/exadata/"
    weight = 3

  [[menu.main]]
    identifier = "automation"
    name = "Automations"
    url = "/automation/"
    weight = 4

  [[menu.main]]
    identifier = "Contact"
    name = "Contact"
    url = "/contact/"
    weight = 5

# Taxonomies
[taxonomies]
  category = "categories"
  tag = "tags"

# Goldmark Markdown renderer
[markup]
  [markup.goldmark.renderer]
    unsafe = true

