baseURL = "https://Sukeshbasedata.github.io/"
title = "SukeshBaseData"
theme = "hugo-PaperMod"
enableRobotsTXT = true

[params]
  author = "Kotha Sukesh Kumar Reddy"
  description = "Oracle, Exadata, PostgreSQL & DBA knowledge shared with DBA tech friends."
  defaultTheme = "auto"          # auto / dark / light
  ShowReadingTime = true
  ShowToc = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowShareButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true

[pagination]
  pagerSize = 10    # replaces deprecated paginate

[menu]
  [[menu.main]]
    identifier = "oracle"
    name = "Oracle"
    url = "/oracle/"
    weight = 1

  [[menu.main]]
    identifier = "postgresql"
    name = "PostgreSQL"
    url = "/postgresql/"
    weight = 2

  [[menu.main]]
    identifier = "exadata"
    name = "Exadata"
    url = "/exadata/"
    weight = 3

  [[menu.main]]
    identifier = "automation"
    name = "Automations"
    url = "/automation/"
    weight = 4

  [[menu.main]]
    identifier = "Contact"
    name = "Contact"
    url = "/contact/"
    weight = 5

[taxonomies]
  category = "categories"
  tag = "tags"

[markup]
  [markup.goldmark.renderer]
    unsafe = true


